### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by reduz** [jpcy/xatlas#2]
Giving it a try with Godot, maybe I missed something, but it crashes on exit with following backtrace:

```
#0  0x00007ffff50c5cc1 in _int_free (have_lock=0, p=<optimized out>, 
    av=0x7ffff5419c40 <main_arena>) at malloc.c:4295
#1  __GI___libc_free (mem=0x555560bdccf0) at malloc.c:3124
#2  0x00005555569144ee in __gnu_cxx::new_allocator<unsigned int>::deallocate (
    this=0x555560c05738, __p=0x555560bdccf0)
    at /usr/include/c++/7/ext/new_allocator.h:125
#3  0x000055555690ea1e in std::allocator_traits<std::allocator<unsigned int> >::deallocate (__a=..., __p=0x555560bdccf0, __n=64)
    at /usr/include/c++/7/bits/alloc_traits.h:462
#4  0x000055555690660c in std::_Vector_base<unsigned int, std::allocator<unsigned int> >::_M_deallocate (this=0x555560c05738, __p=0x555560bdccf0, __n=64)
    at /usr/include/c++/7/bits/stl_vector.h:180
#5  0x00005555569058d9 in std::_Vector_base<unsigned int, std::allocator<unsigned int> >::~_Vector_base (this=0x555560c05738, __in_chrg=<optimized out>)
    at /usr/include/c++/7/bits/stl_vector.h:162
#6  0x0000555556901165 in std::vector<unsigned int, std::allocator<unsigned int> >::~vector (this=0x555560c05738, __in_chrg=<optimized out>)
    at /usr/include/c++/7/bits/stl_vector.h:435
#7  0x00005555568fba4c in xatlas::internal::param::Chart::~Chart (
    this=0x555560c056e0, __in_chrg=<optimized out>)
    at thirdparty/xatlas/xatlas.cpp:5260
#8  0x00005555568fbae7 in xatlas::internal::param::MeshCharts::~MeshCharts (
    this=0x555560a14280, __in_chrg=<optimized out>)
---Type <return> to continue, or q <return> to quit---
    at thirdparty/xatlas/xatlas.cpp:5926
#9  0x00005555568fc999 in xatlas::internal::param::Atlas::~Atlas (
    this=0x555560999810, __in_chrg=<optimized out>)
    at thirdparty/xatlas/xatlas.cpp:6230
#10 0x000055555690103e in xatlas::Atlas::~Atlas (this=0x555560999810, 
    __in_chrg=<optimized out>) at thirdparty/xatlas/xatlas.cpp:7032
#11 0x00005555568e6cf9 in xatlas::Destroy (atlas=0x555560999810)
    at thirdparty/xatlas/xatlas.cpp:7064
```

**Comment by reduz** [comment]
Nevermind, my fault. I corrupted memory.
